// ──────────────────────────────────────────────────────────────────────
//  SITE OFFICIEL DE CHAQUE MARQUE  ·  source des vrais logos
//
//  Une clé du catalogue → le domaine de la marque. C'est tout ce dont fetch-logos.ts a besoin :
//  on ne CHERCHE pas le logo, on va le prendre chez lui. Aucune ambiguïté possible — le logo
//  servi par eau-thermale-avene.fr est celui d'Avène, par construction.
//
//  Une entrée absente d'ici garde sa vignette typographique. Ajouter le domaine puis relancer
//  `npm run logos:recuperer` suffit à la remplacer.
// ──────────────────────────────────────────────────────────────────────

// Marques dont la récupération automatique ramène systématiquement autre chose que le logo
// (photo d'ambiance, bandeau marketing, logo de certification). Elles gardent leur vignette
// typographique et ne sont plus retentées. Rempli par `npm run logos:rejeter -- <clé>`.
export const REJETS: string[] = [
  'caudalie',
  'eafit',
  'la_roche_posay',
  'mustela',   // le site sert une photo de bébés, jamais le logo
];

export const LOGO_SOURCES: Record<string, string> = {
  // ── Dermocosmétique ─────────────────────────────────────────────────
  avene: 'www.eau-thermale-avene.fr',
  la_roche_posay: 'www.laroche-posay.fr',
  bioderma: 'www.bioderma.fr',
  vichy: 'www.vichy.fr',
  uriage: 'www.uriage.com',
  svr: 'www.labo-svr.com',
  ducray: 'www.ducray.com',
  a_derma: 'www.aderma.fr',
  klorane: 'www.klorane.com',
  rene_furterer: 'www.renefurterer.com',
  eucerin: 'www.eucerin.fr',
  cerave: 'www.cerave.fr',
  cetaphil: 'www.cetaphil.fr',
  mustela: 'www.mustela.fr',
  topicrem: 'www.topicrem.com',
  embryolisse: 'www.embryolisse.fr',
  filorga: 'www.filorga.com',
  nuxe: 'www.nuxe.com',
  caudalie: 'fr.caudalie.com',
  lierac: 'www.lierac.fr',
  garancia: 'www.garancia-beaute.com',
  cattier: 'www.cattier-paris.com',
  melvita: 'www.melvita.fr',
  sanoflore: 'www.sanoflore.net',
  weleda: 'www.weleda.fr',
  la_rosee: 'www.larosee-cosmetiques.com',
  laboratoires_de_biarritz: 'www.laboratoires-biarritz.com',
  dermaceutic: 'www.dermaceutic.com',
  acm: 'www.acm-cosmetics.com',
  isispharma: 'www.isispharma.com',
  patyka: 'www.patyka.com',
  neutrogena: 'www.neutrogena.fr',
  nivea: 'www.nivea.fr',
  dove: 'www.dove.com',
  mixa: 'www.mixa.fr',
  sorifa: 'www.sorifa.com',

  // ── Compléments, phyto, micronutrition ──────────────────────────────
  arkopharma: 'www.arkopharma.com',
  puressentiel: 'www.puressentiel.com',
  pranarom: 'www.pranarom.fr',
  pileje: 'www.pileje.fr',
  nutergia: 'www.nutergia.com',
  nhco_nutrition: 'www.nhco-nutrition.com',
  oenobiol: 'www.oenobiol.com',
  ineldea: 'www.ineldea.com',
  granions: 'www.granions.fr',
  solgar: 'www.solgar.fr',
  forte_pharma: 'www.fortepharma.com',
  biocyte: 'www.biocyte.com',
  eric_favre: 'www.ericfavre.com',
  laboratoire_lescuyer: 'www.laboratoire-lescuyer.com',
  super_diet: 'www.superdiet.fr',
  naturactive: 'www.naturactive.fr',
  d_plantes: 'www.dplantes.com',
  bion3: 'www.bion3.fr',
  berocca: 'www.berocca.fr',
  alvityl: 'www.alvityl.com',
  juvamine: 'www.juvamine.com',
  vitavea: 'www.vitavea.com',
  pediakid: 'www.pediakid.com',
  eafit: 'www.eafit.com',
  novoma: 'www.novoma.com',
  nutrisante: 'www.nutrisante.fr',
  therascience: 'www.therascience.com',
  densmore: 'www.densmore.fr',

  // ── Pharmaceutique / OTC ────────────────────────────────────────────
  upsa: 'www.upsa.fr',
  sanofi: 'www.sanofi.fr',
  opella: 'www.opella.com',
  gsk: 'fr.gsk.com',
  haleon: 'www.haleon.com',
  pfizer: 'www.pfizer.fr',
  novartis: 'www.novartis.fr',
  sandoz: 'www.sandoz.fr',
  roche: 'www.roche.fr',
  merck_msd: 'www.msd-france.com',
  bayer: 'www.bayer.fr',
  abbott: 'www.fr.abbott',
  abbvie: 'www.abbvie.fr',
  astrazeneca: 'www.astrazeneca.fr',
  eli_lilly: 'www.lilly.fr',
  johnson_et_johnson: 'www.jnj.com',
  kenvue: 'www.kenvue.com',
  janssen: 'www.janssen.com',
  bristol_myers_squibb: 'www.bms.com',
  boehringer_ingelheim: 'www.boehringer-ingelheim.com',
  takeda: 'www.takeda.com',
  teva: 'www.tevapharm.fr',
  viatris: 'www.viatris.fr',
  mylan: 'www.viatris.fr',
  amgen: 'www.amgen.fr',
  biogen: 'www.biogen.fr',
  ucb: 'www.ucb.com',
  servier: 'servier.fr',
  ipsen: 'www.ipsen.com',
  chiesi: 'www.chiesi.fr',
  menarini: 'www.menarini.fr',
  almirall: 'www.almirall.fr',
  lundbeck: 'www.lundbeck.com',
  organon: 'www.organon.fr',
  novo_nordisk: 'www.novonordisk.fr',
  fresenius_kabi: 'www.fresenius-kabi.com',
  b_braun: 'www.bbraun.fr',
  gedeon_richter: 'www.gedeonrichter.fr',
  recordati: 'www.recordati.com',
  angelini_pharma: 'www.angelinipharma.com',
  zambon: 'www.zambon.com',
  grunenthal: 'www.grunenthal.fr',
  biocodex: 'www.biocodex.fr',
  boiron: 'www.boiron.fr',
  lehning: 'www.lehning.com',
  cooper: 'www.cooper.fr',

  // ── Premiers soins, matériel, hygiène ───────────────────────────────
  urgo_healthcare: 'www.urgo.fr',
  laboratoires_gilbert: 'www.gilbert-laboratoires.com',
  mayoly: 'www.mayoly.com',
  laboratoires_expanscience: 'www.expanscience.com',
  hartmann: 'www.fr.hartmann.info',
  thuasne: 'www.thuasne.com',
  essity: 'www.essity.com',
  asepta: 'www.asepta.com',
  sunstar: 'www.sunstargum.com',
  bausch_lomb: 'www.bausch.com',

  // ── Groupes ─────────────────────────────────────────────────────────
  laboratoires_pierre_fabre: 'www.pierre-fabre.com',
  l_oreal_dermatological_beauty: 'www.loreal.com',
  naos: 'www.naos.com',
  beiersdorf: 'www.beiersdorf.fr',
  laboratoire_native: 'www.laboratoire-native.com',
  groupe_nuxe: 'www.nuxe.com',
  galderma: 'www.galderma.com',
  l_oreal: 'www.loreal.com',
  unilever: 'www.unilever.fr',
  reckitt: 'www.reckitt.com',
  procter_et_gamble: 'fr.pg.com',
  perrigo: 'www.perrigo.com',
  omega_pharma: 'www.perrigo.com',
  sartorius: 'www.sartorius.com',
  philips: 'www.philips.fr',
  medtronic: 'www.medtronic.com',
  thermo_fisher_scientific: 'www.thermofisher.com',
  colgate_palmolive: 'www.colgatepalmolive.fr',
  vendome: 'www.lepetitmarseillais.com',
  tilman: 'www.tilman.be',

  // ── Enrichissement : marques courantes en officine ──────────────────
  roge_cavailles: 'www.rogecavailles.fr',
  noreva: 'www.noreva-dermo.fr',
  bailleul: 'www.laboratoires-bailleul.com',
  gifrer: 'www.gifrer.fr',
  saugella: 'www.saugella.fr',
  dermophil: 'www.dermophil.fr',
  le_petit_marseillais: 'www.lepetitmarseillais.com',
  sanex: 'www.sanex.fr',
  codexial: 'www.codexial.fr',
  sinclair: 'www.sinclair.com',
  thea: 'www.laboratoires-thea.com',
  horus_pharma: 'www.horus-pharma.com',
  alcon: 'www.alcon.com',
  aragan: 'www.aragan.com',
  synergia: 'www.synergiashop.com',
  lero: 'www.lero.fr',
  fleurance_nature: 'www.fleurancenature.fr',
  nat_et_form: 'www.natetform.com',
  dietaroma: 'www.dietaroma.fr',
  vitaflor: 'www.vitaflor.com',
  labcatal: 'www.labcatal.com',
  copmed: 'www.copmed.fr',
  anaca3: 'www.anaca3.com',
  yves_ponroy: 'www.ponroy.com',
  phytoresearch: 'www.phytoresearch.fr',
  crinex: 'www.crinex.fr',
  genevrier: 'www.laboratoires-genevrier.com',
  mercurochrome: 'www.mercurochrome.fr',
  compeed: 'www.compeed.fr',
  hra_pharma: 'www.hra-pharma.com',
  lysopaine: 'www.lysopaine.fr',
  sterimar: 'www.sterimar.com',
  prospan: 'www.prospan.fr',
  humer: 'www.humer.fr',
  dodie: 'www.dodie.fr',
  mam: 'www.mambaby.com',
  avent: 'www.philips.fr',
  gallia: 'www.laboratoire-gallia.com',
  guigoz: 'www.guigoz.fr',
  bledina: 'www.bledina.com',
  nestle_health_science: 'www.nestlehealthscience.fr',
  francodex: 'www.francodex.com',
  virbac: 'www.virbac.fr',
  ceva: 'www.ceva.com',
  elanco: 'www.elanco.com',
  omron: 'www.omron-healthcare.com',
  sigvaris: 'www.sigvaris.com',
  gibaud: 'www.gibaud.com',
  donjoy: 'www.donjoy.fr',
  epitact: 'www.epitact.com',
  scholl: 'www.scholl.fr',
  pediRelax: 'www.pedirelax.fr',
  lifescan: 'www.onetouch.fr',
  roche_diabetes: 'www.accu-chek.fr',
  biotherm: 'www.biotherm.fr',
  lancaster: 'www.lancaster-beauty.com',
  piz_buin: 'www.pizbuin.com',
  alphanova: 'www.alphanova.fr',
};
